config/routes.rb
Rails.application.routes.draw do
  resources :interviews
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interview.rb
class Interview < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]

  # GET /interviews
  # GET /interviews.json
  def index
    @interviews = Interview.all
  end

  # GET /interviews/1
  # GET /interviews/1.json
  def show
  end

  # GET /interviews/new
  def new
    @interview = Interview.new
  end

  # GET /interviews/1/edit
  def edit
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @interview = Interview.new(interview_params)

    respond_to do |format|
      if @interview.save
        format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
        format.json { render :show, status: :created, location: @interview }
      else
        format.html { render :new }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interviews/1
  # PATCH/PUT /interviews/1.json
  def update
    respond_to do |format|
      if @interview.update(interview_params)
        format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
        format.json { render :show, status: :ok, location: @interview }
      else
        format.html { render :edit }
        format.json { render json: @interview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviews/1
  # DELETE /interviews/1.json
  def destroy
    @interview.destroy
    respond_to do |format|
      format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:company_name, :date, :stage, :method, :verdict)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<%= form_with(model: interview, local: true) do |form| %>
  <% if interview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
      <% interview.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :stage %>
    <%= form.number_field :stage %>
  </div>

  <div class="field">
    <%= form.label :method %>
    <%= form.text_field :method %>
  </div>

  <div class="field">
    <%= form.label :verdict %>
    <%= form.text_field :verdict %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interviews</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Date</th>
      <th>Stage</th>
      <th>Method</th>
      <th>Verdict</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interviews.each do |interview| %>
      <tr>
        <td><%= interview.company_name %></td>
        <td><%= interview.date %></td>
        <td><%= interview.stage %></td>
        <td><%= interview.method %></td>
        <td><%= interview.verdict %></td>
        <td><%= link_to 'Show', interview %></td>
        <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
        <td><%= link_to 'Destroy', interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interview', new_interview_path %>

app/views/interviews/new.html.erb
<h1>New Interview</h1>

<%= render 'form', interview: @interview %>

<%= link_to 'Back', interviews_path %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @interview.company_name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @interview.date %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @interview.stage %>
</p>

<p>
  <strong>Method:</strong>
  <%= @interview.method %>
</p>

<p>
  <strong>Verdict:</strong>
  <%= @interview.verdict %>
</p>

<%= link_to 'Edit', edit_interview_path(@interview) %> |
<%= link_to 'Back', interviews_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProspectorRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>